### ISSUE TITLE
Need for Enhancement of the project

### ISSUE THREAD

**Issue by wweverma1** [metakgp/gyft-serve#9]
## While using the web app I felt the need of changes which I'm listing below:

- Security Question not being displayed properly
- No point of displaying "Security Question Answer" input box before validating Roll Number
- No point of displaying "ERP Password" input box before validating Roll Number
- No Need for displaying button for "Add to Google Calendar" before fetching students time table
- Incorrect Icons for input boxes
- image on left side not vertically aligned
- Footer not aligned correctly

I'm willing to work on this and fix these issues.

![Screenshot from 2021-10-02 21-44-01](https://user-images.githubusercontent.com/51537596/135724697-6136b50d-e01e-4543-b582-af6f78784c76.png)

**Comment by wweverma1** [comment]
I've raised a PR against this Issue.
PR : https://github.com/metakgp/gyft-serve/pull/10
Kindly merge it after reviewing.
Also can you please tag "hacktoberfest-accepted" label to it?

**Comment by wweverma1** [comment]
@thealphadollar can you please review this issue?

**Comment by thealphadollar** [comment]
Thanks for tagging me. I'll review the PR soon.
